services:
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: todo   # creates 'todo' database during initialization
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
